--
-- Database: `db_attendancesystem`
--
CREATE DATABASE IF NOT EXISTS `db_attendancesystem` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `db_attendancesystem`;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
